# YAML configuration with secrets for testing GitHub Secret Scanning

apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded secrets (these are still detectable)
  database-password: U3VwZXJTZWNyZXRQYXNzd29yZDEyMyE=
  api-key: c2stdGVzdF80ZUM39HqLyjWDarjtT1zdp7dc

# Plain text secrets in YAML
database:
  host: localhost
  port: 5432
  username: admin
  password: "MyDatabasePassword2024!"

aws:
  access_key_id: "AKIAI44QH8DHBEXAMPLE"
  secret_access_key: "je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY"
  region: "us-west-2"

github:
  personal_access_token: "ghp_abcdef1234567890abcdef1234567890abcdef12"
  app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA1234567890abcdef1234567890abcdef1234567890abcdef
    1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12
    -----END RSA PRIVATE KEY-----

slack:
  bot_token: "xoxb-1234567890-1234567890-abcdefghijklmnopqrstuvwx"
  webhook_url: "https://hooks.slack.com/services/T1234567890/B1234567890/abcdefghijklmnopqrstuvwx"

docker:
  registry_token: "dckr_pat_abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

npm:
  auth_token: "npm_abcdef1234567890abcdef1234567890abcdef123456"

sendgrid:
  api_key: "SG.abcdef1234567890.abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

stripe:
  publishable_key: "pk_test_abcdef1234567890abcdef1234567890abcdef12"
  secret_key: "sk_test_abcdef1234567890abcdef1234567890abcdef12"
